### ISSUE TITLE
Debugging on desktop

### ISSUE THREAD

**Issue by phzbox** [jairajs89/Touchy.js#1]
Hi, I was wondering if you had planed a way to test the App in the desktop? I.e. Faking the ipad movement with the mouse by holding keys or something? Thanks

**Comment by jairajs89** [comment]
I hadn't thought of it before, but it's a great idea. It's on the roadmap now.

**Comment by phzbox** [comment]
Cool, you might want to look at: https://github.com/furf/jquery-ui-touch-punch

**Comment by jairajs89** [comment]
My latest updates provide most of what I think you were looking for. There are some small bugs that I'll fix later, but for now this should be good for you to test in the browser.

```
// Normally invoked like this
Touchy(element, callback); // For any finger events
Touchy(element, { one: ..., two: ... }); // For specific multi-touch events

// Invoked like this to enable mouse simulation
Touchy(element, true, callback);
Touchy(element, true, { one: ..., two: ... });
```

**Comment by phzbox** [comment]
Awesome, thanks!
