### ISSUE TITLE
error line 390

### ISSUE THREAD

**Issue by xem** [jairajs89/Touchy.js#2]
Hi,

on iPad, there is an error line 390 of touchy.js:

your code says:

this.fingers.splice(index, 1);

but this.fingers is undefined.

Instead, I wrote this:

mainHand.fingers.splice(index, 1);

and it solved the problem. But is it the right thing? And btw, why do you do a splice at this place?

Thanks for fixing this.

M.E.

**Comment by jairajs89** [comment]
Nice bug catch! It's fixed in my latest commit.

mainHand holds all the current fingers touching the screen. This function, 'mainHandEnd', is called when a finger from the mainHand is no longer touching the screen, so I remove it from mainHand.fingers (the list of fingers).
