### ISSUE TITLE
wacom multitouch pad web plugin && apple trackpad support ?

### ISSUE THREAD

**Issue by Kuranes** [jairajs89/Touchy.js#4]
latest wacom bamboo and intuos web plugin support code
http://www.wacomeng.com/web/index.html
(another demo here http://www.drawmore.net )

Apple MacBook or MagicPad
https://github.com/borismus/MagicTouch  (from http://www.html5rocks.com/en/mobile/touch/ )

only missing one is "Logitech Wireless Touchpad", cannot find doc on broswer event handling

**Comment by jairajs89** [comment]
I recently added mouse-based touch-event simulation (usage described in README).

I'm hoping to make it more accurate when I have time.
