### ISSUE TITLE
Internet Explorer 8 incompatibility

### ISSUE THREAD

**Issue by RobbinHabermehl** [jairajs89/Touchy.js#7]
Touchy is a great layer for implementing both touch (smartphones and tablets) and click (desktops) events in a webapp. I ran into a problem when testing a webapp of mine on Internet Explorer; the coordinates that the Touchy callback returns are 'undefined'.

Unfortunately Internet Explorer 8 and older versions still have a market share of over 20 percent, such a large group of users is hard to ignore. It would be great if Touchy supports Internet Explorer 8 as well!

**Comment by jairajs89** [comment]
Touchy was explicitly written targeting mobile webapps (specifically webkit-based apps). The click simulation functionality is only there to help develop such apps. As such, IE8 is not exactly the ideal environment for testing modern webkit-based mobile apps and there is no plan to support it.

jQuery (jquery.com) has extensive support for IE (all the way back to IE6) and has cross-platform click events (including mobile). If you're looking for a cross-platform way to get the coordinates of click event, that's probably your best bet.
