### ISSUE TITLE
Host a demo please!!! :)

### ISSUE THREAD

**Issue by Pensive** [jairajs89/Touchy.js#8]
I want to see if this works; the demo is only in a downloadable zip file.

in order to try it with my iPad, I need to download it, upload it to my own host, then load up that url in my iPad. Can you set up a free hosting account somewhere to host the demo rather than just post it on github?

I can do this myself of course, but that means the next person has to do it too, and the next one....and the next one...

ad infinitum.

:)

**Comment by jairajs89** [comment]
Hey!

All development for Touchy.js has now been move to [Touchable.js](https://github.com/kikinteractive/touchable), a fork of mine.

https://github.com/kikinteractive/touchable

The page for the new library has links to hosted demos.
